name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 22

    - run: corepack enable
    - run: corepack install --global pnpm@10.0

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm build
