name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 22

    - name: Install corepack and PNPM
      run: |
        | corepack enable
        | corepack install --global pnpm@10.0

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm build

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: docker build . -t ghcr.io/${{ github.repository }}:latest

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository }}:latest